"""org, product, source, binding

Revision ID: e527dd6eadd6
Revises: 
Create Date: 2026-10-01 17:16:55.876097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from layer.core.config import settings
from layer.db import rls

# revision identifiers, used by Alembic.
revision: str = 'e527dd6eadd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.String(length=64), nullable=True),
    sa.Column('ref_prefix', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('registering', 'sources_bound', 'assertions_confirmed', 'live')", name='ck_product_status'),
    sa.CheckConstraint('onboarding_step BETWEEN 1 AND 7', name='ck_product_onboarding_step'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_product_org_key')
    )
    op.create_index('ix_product_org', 'product', ['org_id'], unique=False)
    op.create_table('binding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('clause_ref', sa.String(length=64), nullable=False),
    sa.Column('metric_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id', 'metric', 'clause_ref', name='uq_binding_metric_clause')
    )
    op.create_index('ix_binding_product', 'binding', ['org_id', 'product_id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pinned_rev', sa.String(length=64), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('spec', 'eval', 'code', 'ticket', 'production', 'decision')", name='ck_source_role'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_product_role', 'source', ['org_id', 'product_id', 'role'], unique=False)
    # ### end Alembic commands ###

    # Isolation lands with the tables, never in a follow-up migration: a window
    # where tenant tables exist without a policy is a window where a leak is legal.
    # Named explicitly, not taken from the live model: this migration must keep
    # describing the three tables it created, whatever the schema grows into.
    tables = ("product", "source", "binding")
    role = rls.app_role_from_url(settings.database_url)
    for statement in rls.enable_statements(tables) + rls.grant_statements(role, tables):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    tables = ("product", "source", "binding")
    role = rls.app_role_from_url(settings.database_url)
    for statement in rls.revoke_statements(role, tables) + rls.disable_statements(tables):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_product_role', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_binding_product', table_name='binding')
    op.drop_table('binding')
    op.drop_index('ix_product_org', table_name='product')
    op.drop_table('product')
    op.drop_table('org')
    # ### end Alembic commands ###
