"""clause, observation, enforcement, link, entity, proposal, audit

Revision ID: e56fae9886ab
Revises: e527dd6eadd6
Create Date: 2026-10-01 18:15:32.007318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits `pgvector.sqlalchemy.vector.VECTOR(...)` without importing it.
import pgvector.sqlalchemy

from layer.core.config import settings
from layer.db import rls
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e56fae9886ab'
down_revision: Union[str, Sequence[str], None] = 'e527dd6eadd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_event', ['org_id', 'actor', 'created_at'], unique=False)
    op.create_index('ix_audit_subject', 'audit_event', ['org_id', 'subject'], unique=False)
    op.create_table('clause_identity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id', 'identity_key', name='uq_identity_key'),
    sa.UniqueConstraint('org_id', 'product_id', 'ref', name='uq_identity_ref')
    )
    op.create_table('proposal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=16), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('if_rejected', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('critic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('proposed_by', sa.String(length=255), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state = 'open' AND decided_by IS NULL AND decided_at IS NULL) OR (state <> 'open' AND decided_by IS NOT NULL AND decided_at IS NOT NULL)", name='ck_proposal_decision_record'),
    sa.CheckConstraint("state IN ('open', 'accepted', 'rejected')", name='ck_proposal_state'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposal_state', 'proposal', ['org_id', 'state'], unique=False)
    op.create_index('uq_proposal_one_open_per_target', 'proposal', ['org_id', 'target', 'field'], unique=True, postgresql_where=sa.text("state = 'open'"))
    op.create_table('clause',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('metric', sa.String(length=128), nullable=True),
    sa.Column('comparator', sa.String(length=8), nullable=True),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('value_high', sa.Double(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('verdict_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_locator', sa.String(length=512), nullable=True),
    sa.Column('statement_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("comparator IS DISTINCT FROM 'between' OR (value IS NOT NULL AND value_high IS NOT NULL)", name='ck_clause_band_has_both_ends'),
    sa.CheckConstraint("comparator IS NULL OR comparator IN ('>=', '<=', '==', 'between')", name='ck_clause_comparator'),
    sa.CheckConstraint("state IN ('provisional', 'measured', 'ratified')", name='ck_clause_state'),
    sa.CheckConstraint("status IN ('active', 'superseded')", name='ck_clause_status'),
    sa.CheckConstraint("verdict IN ('met', 'missed', 'cannot_confirm', 'not_applicable', 'not_measured')", name='ck_clause_verdict'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['clause.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id', 'ref', 'version', name='uq_clause_ref_version')
    )
    op.create_index('ix_clause_metric', 'clause', ['org_id', 'product_id', 'metric'], unique=False)
    op.create_index('ix_clause_product_active', 'clause', ['org_id', 'product_id', 'status'], unique=False)
    op.create_table('enforcement_fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('enforced', sa.Boolean(), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('partial_note', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Double(), nullable=True),
    sa.Column('comparator', sa.String(length=8), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('workflow', sa.String(length=512), nullable=True),
    sa.Column('known_failing', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('all_runs', 'latest_only', 'latest_shipped')", name='ck_enforcement_scope'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id', 'metric', 'file', 'line', name='uq_enforcement_site')
    )
    op.create_index('ix_enforcement_metric', 'enforcement_fact', ['org_id', 'product_id', 'metric'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'superseded')", name='ck_entity_status'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'entity_type', 'ref', 'version', name='uq_entity_ref_version')
    )
    op.create_index('ix_entity_type', 'entity', ['org_id', 'entity_type', 'status'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('from_ref', sa.String(length=255), nullable=False),
    sa.Column('to_ref', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'retracted')", name='ck_link_status'),
    sa.CheckConstraint('from_ref <> to_ref', name='ck_link_not_self'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'from_ref', 'to_ref', 'link_type', name='uq_link_edge')
    )
    op.create_index('ix_link_from', 'link', ['org_id', 'from_ref'], unique=False)
    op.create_index('ix_link_to', 'link', ['org_id', 'to_ref'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('clause_ref', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('corpus_sha', sa.String(length=64), nullable=True),
    sa.Column('code_rev', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('run_url', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_kind IN ('eval', 'production')", name='ck_obs_source_kind'),
    sa.CheckConstraint('total IS NULL OR (total >= 0 AND passed IS NOT NULL AND passed BETWEEN 0 AND total)', name='ck_obs_passed_within_total'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'product_id', 'clause_ref', 'metric', 'run_url', name='uq_observation_idempotent', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_obs_clause', 'observation', ['org_id', 'clause_ref', 'metric', 'measured_at'], unique=False)
    op.create_index('ix_obs_series', 'observation', ['org_id', 'product_id', 'metric', 'measured_at'], unique=False)
    # ### end Alembic commands ###

    # Isolation and append-only land with the tables, for the same reason as in
    # migration 1: a window where these exist unprotected is a window where a leak
    # or a silent audit edit is legal.
    new_tables = ('clause', 'clause_identity', 'observation', 'enforcement_fact', 'entity', 'proposal', 'link', 'audit_event')
    role = rls.app_role_from_url(settings.database_url)
    for statement in (
        rls.enable_statements(new_tables)
        + rls.grant_statements(role, new_tables)
        + rls.append_only_statements(("audit_event",))
    ):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    new_tables = ('clause', 'clause_identity', 'observation', 'enforcement_fact', 'entity', 'proposal', 'link', 'audit_event')
    role = rls.app_role_from_url(settings.database_url)
    for statement in (
        rls.drop_append_only_statements(("audit_event",), drop_function=True)
        + rls.revoke_statements(role, new_tables)
        + rls.disable_statements(new_tables)
    ):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_series', table_name='observation')
    op.drop_index('ix_obs_clause', table_name='observation')
    op.drop_table('observation')
    op.drop_index('ix_link_to', table_name='link')
    op.drop_index('ix_link_from', table_name='link')
    op.drop_table('link')
    op.drop_index('ix_entity_type', table_name='entity')
    op.drop_table('entity')
    op.drop_index('ix_enforcement_metric', table_name='enforcement_fact')
    op.drop_table('enforcement_fact')
    op.drop_index('ix_clause_product_active', table_name='clause')
    op.drop_index('ix_clause_metric', table_name='clause')
    op.drop_table('clause')
    op.drop_index('uq_proposal_one_open_per_target', table_name='proposal', postgresql_where=sa.text("state = 'open'"))
    op.drop_index('ix_proposal_state', table_name='proposal')
    op.drop_table('proposal')
    op.drop_table('clause_identity')
    op.drop_index('ix_audit_subject', table_name='audit_event')
    op.drop_index('ix_audit_actor', table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
